[ host_req ]
distinguished_name  = host_req_distinguished_name
x509_extensions     = host_ext
req_extensions      = host_ext

# Use CN variable for CommonName
[ host_req_distinguished_name ]
CN=$ENV::CN

# Use CN variable for DNS
[ host_ext ]
basicConstraints = critical,CA:false
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=critical,serverAuth
subjectAltName=critical,DNS:$ENV::CN